# Generated by Django 5.2.3 on 2026-09-27 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'types',
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('generation', models.IntegerField()),
                ('type1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type1_pokemon', to='pokesearch.type')),
                ('type2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type2_pokemon', to='pokesearch.type')),
            ],
            options={
                'verbose_name': 'Pokemon',
                'verbose_name_plural': 'Pokemon',
                'db_table': 'pokemon',
            },
        ),
    ]
